version: "3.8"

services:

  jellyfin-tubearchivist-sync:

    build: .

    container_name: jellyfintubesync

    restart: unless-stopped

    environment:
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}

      JELLYFIN_URL: ${JELLYFIN_URL}
      JELLYFIN_API: ${JELLYFIN_API}
      JELLYFIN_USER_ID: ${JELLYFIN_USER_ID}

      TUBEARCHIVIST_URL: ${TUBEARCHIVIST_URL}
      TUBEARCHIVIST_API: ${TUBEARCHIVIST_API}

    dns:
      - 1.1.1.1
      - 1.0.0.1

    networks:
      - shared_network

    mem_limit: 256m
    mem_reservation: 128m

    cpus: 0.50

    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  shared_network:
    external: true